import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite';

const here = fileURLToPath(new URL('.', import.meta.url));

/**
 * `content/dom-agent.js` 的构建。
 *
 * 产物**提交进仓库**：扩展是解包加载的，加载的就是 `extensions/ccs-fetch-proxy/` 这个目录本身，
 * 没有构建产物就装不起来。文件头的 GENERATED 标记由本配置注入。
 *
 * 单文件 IIFE 而不是 ESM：内容脚本不支持 `type="module"` 的动态 import 拆包，
 * manifest 里那一行只吃一个普通脚本。
 */

/** 与 apps/ccs-framework/vite.config.ts 同款：SDK 源码调试模式 */
const SDK = process.env.WEBSKILL_SRC;
const sdkRoot = SDK === undefined ? undefined : resolve(here, SDK);
if (sdkRoot !== undefined && !existsSync(sdkRoot)) {
  throw new Error(`WEBSKILL_SRC does not exist: ${sdkRoot}`);
}

/** @webskill/sdk 子路径 → SDK 仓库内的包目录名 */
const SUBPATHS = { browser: 'browser', agent: 'agent', core: 'core', runtime: 'runtime', mcp: 'mcp' };

function webskillAlias() {
  if (sdkRoot === undefined) return [];
  const pkg = (name) => resolve(sdkRoot, `packages/${name}/src/index.ts`);
  // 子路径必须排在根路径之前，否则 '@webskill/sdk/browser' 会被前缀匹配成 sdk + '/browser'
  const alias = Object.entries(SUBPATHS).map(([sub, name]) => ({
    find: `@webskill/sdk/${sub}`,
    replacement: pkg(name)
  }));
  alias.push({ find: '@webskill/sdk', replacement: resolve(sdkRoot, 'packages/sdk/src/index.ts') });
  for (const name of Object.values(SUBPATHS)) alias.push({ find: `@webskill/${name}`, replacement: pkg(name) });
  return alias;
}

export default defineConfig({
  resolve: { alias: webskillAlias() },
  build: {
    outDir: 'content',
    emptyOutDir: false,
    // 内容脚本没有模块作用域，压缩后仍是全局脚本；保留可读的换行便于线上排查
    minify: 'esbuild',
    lib: {
      entry: resolve(here, 'src/domAgent.ts'),
      formats: ['iife'],
      name: 'ccsDomAgent',
      fileName: () => 'dom-agent.js'
    },
    rollupOptions: {
      output: {
        banner: '// GENERATED by `pnpm --filter ccs-fetch-proxy build` from src/domAgent.ts — do not edit.',
        extend: true
      }
    }
  }
});
