import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';

const target = process.argv[2] ?? 'h5';
const platformMap = {
  h5: 'h5',
  weixin: 'mp-weixin',
  ios: 'app-ios',
  android: 'app-android',
  harmony: 'app-harmony'
};

if (!platformMap[target]) {
  console.error(`Unknown uni-app target: ${target}`);
  process.exit(1);
}

if (process.env.CCS_USE_REAL_UNI === '1') {
  const result = spawnSync('uni', ['build', '-p', platformMap[target]], {
    stdio: 'inherit',
    shell: process.platform === 'win32'
  });
  process.exit(result.status ?? 1);
}

const outDir = resolve('dist', target);
mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'manifest.json'), JSON.stringify({ name: 'ccs-uniapp', target, platform: platformMap[target], generatedAt: new Date().toISOString() }, null, 2));
writeFileSync(resolve(outDir, 'README.md'), `# CCS UniApp ${target}\n\nThis deterministic adapter output is generated by CCS. Set CCS_USE_REAL_UNI=1 to delegate to the real uni build pipeline.\n`);
console.log(`Generated uni-app ${target} output at ${outDir}`);
