import { spawnSync } from 'node:child_process';
import { copyFileSync, cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';

const target = process.argv[2] ?? 'h5';
const repoRoot = process.env.CCS_REPO_ROOT ? resolve(process.env.CCS_REPO_ROOT) : resolve('../..');
loadEnvFile(join(repoRoot, '.env'));

const platformMap = {
  h5: 'h5',
  weixin: 'mp-weixin',
  ios: 'app-ios',
  android: 'app-android',
  harmony: 'app-harmony'
};

if (!platformMap[target]) {
  console.error(`Unknown uni-app target: ${target}`);
  process.exit(1);
}

const outDir = resolve(process.env.CCS_UNIAPP_OUT_DIR ?? resolve('dist', target));
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const shouldRunUniBuild = process.env.CCS_USE_REAL_UNI === '1' || (target === 'android' && process.env.CCS_USE_REAL_UNI !== '0');

if (shouldRunUniBuild) {
  if (target === 'android') validateAndroidPackagingEnv();

  const result = spawnSync('pnpm', ['exec', 'uni', 'build', '-p', platformMap[target]], {
    stdio: 'inherit',
    shell: process.platform === 'win32'
  });
  if (result.status !== 0) process.exit(result.status ?? 1);

  if (target === 'android') {
    packAndroidApk(outDir);
  } else {
    writeMetadata(outDir);
  }

  console.log(`Generated uni-app ${target} output at ${outDir}`);
  process.exit(0);
}

writeMetadata(outDir);

if (target === 'android') {
  console.error('Android builds must use the real uni-app + official DCloud Android offline SDK pipeline. Set CCS_USE_REAL_UNI=1 or leave it unset.');
  process.exit(1);
}

console.log(`Generated uni-app ${target} output at ${outDir}`);

function writeMetadata(dir) {
  const manifest = { name: 'ccs-uniapp', target, platform: platformMap[target], generatedAt: new Date().toISOString() };
  writeFileSync(join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
  const description = target === 'android'
    ? 'Android APK output is generated by the official DCloud Android offline SDK project.'
    : 'This deterministic adapter output is generated by CCS. Set CCS_USE_REAL_UNI=1 to delegate to the real uni build pipeline.';
  writeFileSync(join(dir, 'README.md'), `# CCS UniApp ${target}\n\n${description}\n`);
  return manifest;
}

function collectAndroidApks(dir, packWorkDir = resolve('dist')) {
  let apkFiles = findFiles(packWorkDir, (file) => file.endsWith('.apk') && file.includes(`${join('build', 'outputs', 'apk')}`) && /release/i.test(file));
  if (apkFiles.length === 0) {
    apkFiles = [
      ...findFiles(resolve('unpackage'), (file) => file.endsWith('.apk')),
      ...findFiles(packWorkDir, (file) => file.endsWith('.apk'))
    ];
  }

  writeMetadata(dir);
  if (apkFiles.length === 0) {
    console.error('Android build completed, but no APK was emitted.');
    process.exit(1);
  }

  for (const apk of apkFiles) {
    copyFileSync(apk, join(dir, basename(apk)));
  }
}

function findFiles(dir, predicate, results = []) {
  if (!existsSync(dir)) return results;

  for (const entry of readdirSync(dir)) {
    const file = join(dir, entry);
    const stat = statSync(file);
    if (stat.isDirectory()) {
      findFiles(file, predicate, results);
    } else if (predicate(file)) {
      results.push(file);
    }
  }

  return results;
}

function packAndroidApk(dir) {
  validateAndroidPackagingEnv();

  const sdk = getAndroidSdk();
  const appKey = getAndroidAppKey();
  const appId = readDCloudAppId();
  const applicationId = getAndroidApplicationId();
  const javaHome = getJavaHome();
  const officialProjectDir = findDCloudAndroidProjectDir();
  const packWorkDir = resolve('dist/dcloud-offline-android');
  const gradleUserHome = prepareGradleUserHome(packWorkDir);
  const appDist = resolve('dist/build/app');
  if (!existsSync(appDist)) {
    console.error(`uni-app Android resources were not found at ${appDist}`);
    process.exit(1);
  }

  rmSync(packWorkDir, { recursive: true, force: true });
  copyOfficialProject(officialProjectDir, packWorkDir);

  const moduleDir = findAndroidAppModuleDir(packWorkDir);
  prepareOfficialAndroidProject({
    moduleDir,
    projectDir: packWorkDir,
    appDist,
    appId,
    appKey,
    applicationId,
    sdk
  });

  const gradle = getGradleCommand(packWorkDir);
  const result = spawnSync(gradle.command, gradle.args, {
    cwd: packWorkDir,
    stdio: 'inherit',
    shell: process.platform === 'win32',
    env: withAndroidBuildEnv(process.env, javaHome, gradleUserHome)
  });
  if (result.status !== 0) process.exit(result.status ?? 1);

  collectAndroidApks(dir, packWorkDir);
}

function validateAndroidPackagingEnv() {
  const sdk = getAndroidSdk();
  if (!sdk) {
    console.error('Android SDK is required for APK packaging. Set ANDROID_HOME, ANDROID_SDK_ROOT, CCS_ANDROID_SDK, ANDROID_SDK, or ANDROID_SDK_PATH.');
    process.exit(1);
  }

  if (!existsSync(sdk)) {
    console.error(`Android SDK path does not exist: ${sdk}`);
    process.exit(1);
  }

  if (!findDCloudAndroidProjectDir()) {
    console.error('DCloud official Android offline SDK project is required. Set CCS_DCLOUD_ANDROID_PROJECT_DIR, DCLOUD_ANDROID_PROJECT_DIR, CCS_DCLOUD_ANDROID_SDK_DIR, or DCLOUD_ANDROID_SDK_DIR to the official HBuilder-Integrate-AS/simpleDemo Gradle project path.');
    process.exit(1);
  }

  if (!getAndroidAppKey()) {
    console.error('DCloud offline Android AppKey is required. Set CCS_ANDROID_APP_KEY, DCLOUD_APP_KEY, DCLOUD_ANDROID_APP_KEY, UNI_ANDROID_APP_KEY, or ANDROID_APP_KEY.');
    process.exit(1);
  }

  if (!getAndroidApplicationId()) {
    console.error('Android package name is required. Set CCS_ANDROID_APPLICATION_ID, ANDROID_APPLICATION_ID, or DCLOUD_ANDROID_APPLICATION_ID to the package name registered for the DCloud AppKey.');
    process.exit(1);
  }

  if (!getAndroidKeystoreFile() || !existsSync(resolve(getAndroidKeystoreFile()))) {
    console.error('Android keystore file is required. Set CCS_ANDROID_KEYSTORE_FILE, ANDROID_KEYSTORE_FILE, or DCLOUD_ANDROID_KEYSTORE_FILE to an existing keystore path.');
    process.exit(1);
  }

  if (!getAndroidKeystoreAlias() || !getAndroidKeystorePassword()) {
    console.error('Android keystore alias and password are required. Set CCS_ANDROID_KEYSTORE_ALIAS and CCS_ANDROID_KEYSTORE_PASSWORD, or their ANDROID_/DCLOUD_ aliases.');
    process.exit(1);
  }

  const dcloudAppId = readDCloudAppId();
  if (!dcloudAppId || dcloudAppId === '__UNI__CCSAPP') {
    console.error('DCloud appid is not configured. Update apps/ccs-uniapp/manifest.json and apps/ccs-uniapp/src/manifest.json from the placeholder __UNI__CCSAPP to the real DCloud appid.');
    process.exit(1);
  }

  const javaHome = getJavaHome();
  requireSuccessfulCommand(getJavaBinary('java', javaHome), ['-version'], 'A working JDK 8/11/17 is required for Gradle APK packaging.');
}

function copyOfficialProject(source, target) {
  cpSync(source, target, {
    recursive: true,
    filter(sourcePath) {
      const name = basename(sourcePath);
      return !['.gradle', 'build', '.idea', '.DS_Store'].includes(name);
    }
  });
}

function findAndroidAppModuleDir(projectDir) {
  const manifestFiles = findFiles(projectDir, (file) => file.endsWith(join('src', 'main', 'AndroidManifest.xml')));
  for (const manifestFile of manifestFiles) {
    const moduleDir = dirname(dirname(dirname(manifestFile)));
    const buildFile = join(moduleDir, 'build.gradle');
    if (!existsSync(buildFile)) continue;
    const buildText = readFileSync(buildFile, 'utf8');
    if (buildText.includes('com.android.application')) return moduleDir;
  }

  console.error(`Unable to find an Android application module under ${projectDir}. Expected a module with build.gradle and src/main/AndroidManifest.xml.`);
  process.exit(1);
}

function prepareOfficialAndroidProject({ moduleDir, projectDir, appDist, appId, appKey, applicationId, sdk }) {
  writeFileSync(join(projectDir, 'local.properties'), `sdk.dir=${escapePropertiesValue(sdk)}\n`);

  const appAssetsDir = join(moduleDir, 'src', 'main', 'assets', 'apps');
  rmSync(appAssetsDir, { recursive: true, force: true });
  const wwwDir = join(appAssetsDir, appId, 'www');
  mkdirSync(wwwDir, { recursive: true });
  cpSync(appDist, wwwDir, { recursive: true });

  const controlFile = join(moduleDir, 'src', 'main', 'assets', 'data', 'dcloud_control.xml');
  mkdirSync(dirname(controlFile), { recursive: true });
  writeFileSync(controlFile, `\n<hbuilder>\n<apps>\n    <app appid="${escapeXml(appId)}" appver=""/>\n</apps>\n</hbuilder>\n`);

  updateAndroidManifest(join(moduleDir, 'src', 'main', 'AndroidManifest.xml'), applicationId, appKey);
  updateModuleBuildGradle(join(moduleDir, 'build.gradle'), applicationId);
}

function updateAndroidManifest(file, applicationId, appKey) {
  let text = readFileSync(file, 'utf8');
  text = text.replace(/package="[^"]*"/, `package="${escapeXml(applicationId)}"`);

  if (/android:name="dcloud_appkey"[\s\S]*?android:value="[^"]*"/.test(text)) {
    text = text.replace(/(android:name="dcloud_appkey"[\s\S]*?android:value=")[^"]*(")/, `$1${escapeXml(appKey)}$2`);
  } else {
    text = text.replace(/(<application\b[^>]*>)/, `$1\n        <meta-data android:name="dcloud_appkey" android:value="${escapeXml(appKey)}" />`);
  }

  writeFileSync(file, text);
}

function updateModuleBuildGradle(file, applicationId) {
  let text = readFileSync(file, 'utf8');

  if (/applicationId\s+["'][^"']*["']/.test(text)) {
    text = text.replace(/applicationId\s+["'][^"']*["']/, `applicationId "${escapeGradleString(applicationId)}"`);
  } else if (/defaultConfig\s*\{/.test(text)) {
    text = text.replace(/defaultConfig\s*\{/, `defaultConfig {\n        applicationId "${escapeGradleString(applicationId)}"`);
  } else {
    text += `\nandroid {\n    defaultConfig {\n        applicationId "${escapeGradleString(applicationId)}"\n    }\n}\n`;
  }

  if (/namespace\s+["'][^"']*["']/.test(text)) {
    text = text.replace(/namespace\s+["'][^"']*["']/, `namespace "${escapeGradleString(applicationId)}"`);
  }

  text += `

android {
    signingConfigs {
        ccsRelease {
            storeFile file("${escapeGradleString(resolve(getAndroidKeystoreFile()))}")
            storePassword "${escapeGradleString(getAndroidKeystorePassword())}"
            keyAlias "${escapeGradleString(getAndroidKeystoreAlias())}"
            keyPassword "${escapeGradleString(getAndroidKeyPassword())}"
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.ccsRelease
        }
        release {
            signingConfig signingConfigs.ccsRelease
        }
    }
}
`;

  writeFileSync(file, text);
}

function getGradleCommand(projectDir) {
  const wrapper = join(projectDir, process.platform === 'win32' ? 'gradlew.bat' : 'gradlew');
  if (existsSync(wrapper)) {
    return process.platform === 'win32'
      ? { command: wrapper, args: ['assembleRelease'] }
      : { command: 'sh', args: [wrapper, 'assembleRelease'] };
  }
  return { command: 'gradle', args: ['assembleRelease'] };
}

function prepareGradleUserHome(dir) {
  const gradleUserHome = join(dir, '.gradle');
  mkdirSync(gradleUserHome, { recursive: true });
  writeFileSync(join(gradleUserHome, 'init.gradle'), `
def ccsRepositories = {
    maven { url 'https://maven.aliyun.com/repository/google' }
    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://maven.aliyun.com/repository/jcenter' }
    maven { url 'https://repo.huaweicloud.com/repository/maven/' }
    google()
    mavenCentral()
    jcenter()
}

allprojects {
    buildscript {
        repositories {
            ccsRepositories.delegate = delegate
            ccsRepositories()
        }
    }
    repositories {
        ccsRepositories.delegate = delegate
        ccsRepositories()
    }
}
`);
  return gradleUserHome;
}

function requireSuccessfulCommand(command, args, message) {
  const result = spawnSync(command, args, {
    stdio: 'pipe',
    shell: process.platform === 'win32'
  });

  if (result.status !== 0) {
    const details = Buffer.concat([result.stdout ?? Buffer.alloc(0), result.stderr ?? Buffer.alloc(0)]).toString().trim();
    console.error(message);
    if (details) console.error(details);
    process.exit(result.status ?? 1);
  }
}

function loadEnvFile(file) {
  if (!existsSync(file)) return;

  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const match = trimmed.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;

    const [, key, rawValue] = match;
    if (process.env[key] !== undefined) continue;

    process.env[key] = unwrapEnvValue(rawValue.trim());
  }
}

function unwrapEnvValue(value) {
  if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
    return value.slice(1, -1);
  }
  return value;
}

function getAndroidSdk() {
  return getFirstEnv('CCS_ANDROID_SDK', 'ANDROID_HOME', 'ANDROID_SDK_ROOT', 'ANDROID_SDK', 'ANDROID_SDK_PATH');
}

function getAndroidAppKey() {
  return getFirstEnv('CCS_ANDROID_APP_KEY', 'DCLOUD_APP_KEY', 'DCLOUD_ANDROID_APP_KEY', 'UNI_ANDROID_APP_KEY', 'ANDROID_APP_KEY');
}

function getAndroidApplicationId() {
  return getFirstEnv('CCS_ANDROID_APPLICATION_ID', 'ANDROID_APPLICATION_ID', 'DCLOUD_ANDROID_APPLICATION_ID');
}

function getAndroidKeystoreFile() {
  return getFirstEnv('CCS_ANDROID_KEYSTORE_FILE', 'ANDROID_KEYSTORE_FILE', 'DCLOUD_ANDROID_KEYSTORE_FILE');
}

function getAndroidKeystoreAlias() {
  return getFirstEnv('CCS_ANDROID_KEYSTORE_ALIAS', 'ANDROID_KEYSTORE_ALIAS', 'DCLOUD_ANDROID_KEYSTORE_ALIAS');
}

function getAndroidKeystorePassword() {
  return getFirstEnv('CCS_ANDROID_KEYSTORE_PASSWORD', 'ANDROID_KEYSTORE_PASSWORD', 'DCLOUD_ANDROID_KEYSTORE_PASSWORD');
}

function getAndroidKeyPassword() {
  return getFirstEnv('CCS_ANDROID_KEY_PASSWORD', 'ANDROID_KEY_PASSWORD', 'DCLOUD_ANDROID_KEY_PASSWORD') ?? getAndroidKeystorePassword();
}

function findDCloudAndroidProjectDir() {
  const configured = getFirstEnv('CCS_DCLOUD_ANDROID_PROJECT_DIR', 'DCLOUD_ANDROID_PROJECT_DIR', 'CCS_DCLOUD_ANDROID_SDK_DIR', 'DCLOUD_ANDROID_SDK_DIR');
  if (!configured) return undefined;

  const root = resolve(configured);
  if (isGradleAndroidProject(root)) return root;

  const parent = dirname(root);
  if (isGradleAndroidProject(parent)) return parent;

  const candidates = findFiles(root, (file) => basename(file) === 'settings.gradle').map(dirname);
  return candidates.find(isGradleAndroidProject);
}

function isGradleAndroidProject(dir) {
  return existsSync(join(dir, 'settings.gradle')) && findFiles(dir, (file) => file.endsWith(join('src', 'main', 'AndroidManifest.xml'))).length > 0;
}

function readDCloudAppId() {
  const configured = getFirstEnv('CCS_DCLOUD_APPID', 'DCLOUD_APPID', 'UNI_APPID', 'DCloud_APPID');
  if (configured) return configured;

  for (const manifestFile of [resolve('manifest.json'), resolve('src/manifest.json')]) {
    if (!existsSync(manifestFile)) continue;
    const appid = JSON.parse(readFileSync(manifestFile, 'utf8')).appid;
    if (appid) return appid;
  }
  return undefined;
}

function getJavaHome() {
  const configured = getFirstEnv('CCS_JAVA_HOME', 'JAVA_HOME');
  const configuredHome = normalizeJavaHome(configured);
  if (configuredHome && existsSync(getJavaBinary('java', configuredHome))) return configuredHome;

  const candidates = [
    '/opt/homebrew/opt/openjdk@17',
    '/opt/homebrew/opt/openjdk@11',
    '/opt/homebrew/opt/openjdk@8',
    '/usr/local/opt/openjdk@17',
    '/usr/local/opt/openjdk@11',
    '/usr/local/opt/openjdk@8'
  ];
  return candidates.map(normalizeJavaHome).find((candidate) => candidate && existsSync(getJavaBinary('java', candidate)));
}

function getJavaBinary(binary, javaHome) {
  return javaHome ? join(javaHome, 'bin', binary) : binary;
}

function normalizeJavaHome(javaHome) {
  if (!javaHome) return undefined;

  const macOsJdkHome = join(javaHome, 'libexec', 'openjdk.jdk', 'Contents', 'Home');
  if (existsSync(getJavaBinary('java', macOsJdkHome))) return macOsJdkHome;

  return javaHome;
}

function withAndroidBuildEnv(env, javaHome, gradleUserHome) {
  if (!javaHome) return env;
  return {
    ...env,
    JAVA_HOME: javaHome,
    GRADLE_USER_HOME: gradleUserHome,
    PATH: `${join(javaHome, 'bin')}:${env.PATH ?? ''}`
  };
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function escapeGradleString(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function escapePropertiesValue(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/:/g, '\\:');
}

function getFirstEnv(...names) {
  for (const name of names) {
    const value = process.env[name];
    if (value) return value;
  }
  return undefined;
}
