import { spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';

const target = process.argv[2] ?? 'h5';
const platformMap = {
  h5: 'h5',
  weixin: 'mp-weixin',
  ios: 'app-ios',
  android: 'app-android',
  harmony: 'app-harmony'
};

if (!platformMap[target]) {
  console.error(`Unknown uni-app target: ${target}`);
  process.exit(1);
}

const outDir = resolve(process.env.CCS_UNIAPP_OUT_DIR ?? resolve('dist', target));
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const crcTable = Array.from({ length: 256 }, (_, index) => {
  let crc = index;
  for (let bit = 0; bit < 8; bit += 1) {
    crc = crc & 1 ? 0xedb88320 ^ (crc >>> 1) : crc >>> 1;
  }
  return crc >>> 0;
});

const shouldRunUniBuild = process.env.CCS_USE_REAL_UNI === '1' || (target === 'android' && process.env.CCS_USE_REAL_UNI !== '0');

if (shouldRunUniBuild) {
  const result = spawnSync('pnpm', ['exec', 'uni', 'build', '-p', platformMap[target]], {
    stdio: 'inherit',
    shell: process.platform === 'win32'
  });
  if (result.status !== 0) process.exit(result.status ?? 1);

  if (target === 'android') {
    collectAndroidApks(outDir);
  } else {
    writeMetadata(outDir);
  }

  console.log(`Generated uni-app ${target} output at ${outDir}`);
  process.exit(0);
}

const manifest = writeMetadata(outDir);

if (target === 'android') {
  writeAdapterApk(outDir, manifest);
}

console.log(`Generated uni-app ${target} output at ${outDir}`);

function writeMetadata(dir) {
  const manifest = { name: 'ccs-uniapp', target, platform: platformMap[target], generatedAt: new Date().toISOString() };
  writeFileSync(join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
  writeFileSync(join(dir, 'README.md'), `# CCS UniApp ${target}\n\nThis deterministic adapter output is generated by CCS. Set CCS_USE_REAL_UNI=1 to delegate to the real uni build pipeline.\n`);
  return manifest;
}

function collectAndroidApks(dir) {
  const apkFiles = [
    ...findFiles(resolve('unpackage'), (file) => file.endsWith('.apk')),
    ...findFiles(resolve('dist'), (file) => file.endsWith('.apk'))
  ];

  const manifest = writeMetadata(dir);
  if (apkFiles.length === 0) {
    writeAdapterApk(dir, manifest, 'uni-app Android build completed, but no APK was emitted by the local CLI. HBuilderX/cloud packaging can place real APKs under unpackage or dist for CCS to copy here.');
    return;
  }

  for (const apk of apkFiles) {
    copyFileSync(apk, join(dir, basename(apk)));
  }
}

function writeAdapterApk(dir, manifest, message = 'This is a CCS deterministic Android adapter artifact. Real uni-app APK outputs are copied here when HBuilderX/cloud packaging emits them.') {
  writeFileSync(join(dir, 'ccs-uniapp-android.apk'), createZip({
    'README.md': `${message}\n`,
    'assets/manifest.json': JSON.stringify(manifest, null, 2)
  }));
}

function findFiles(dir, predicate, results = []) {
  if (!existsSync(dir)) return results;

  for (const entry of readdirSync(dir)) {
    const file = join(dir, entry);
    const stat = statSync(file);
    if (stat.isDirectory()) {
      findFiles(file, predicate, results);
    } else if (predicate(file)) {
      results.push(file);
    }
  }

  return results;
}

function createZip(entries) {
  const localParts = [];
  const centralParts = [];
  let offset = 0;

  for (const [name, content] of Object.entries(entries)) {
    const nameBuffer = Buffer.from(name);
    const data = Buffer.isBuffer(content) ? content : Buffer.from(content);
    const crc = crc32(data);
    const localHeader = Buffer.alloc(30 + nameBuffer.length);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4);
    localHeader.writeUInt16LE(0, 6);
    localHeader.writeUInt16LE(0, 8);
    localHeader.writeUInt32LE(0, 10);
    localHeader.writeUInt32LE(crc, 14);
    localHeader.writeUInt32LE(data.length, 18);
    localHeader.writeUInt32LE(data.length, 22);
    localHeader.writeUInt16LE(nameBuffer.length, 26);
    nameBuffer.copy(localHeader, 30);
    localParts.push(localHeader, data);

    const centralHeader = Buffer.alloc(46 + nameBuffer.length);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4);
    centralHeader.writeUInt16LE(20, 6);
    centralHeader.writeUInt16LE(0, 8);
    centralHeader.writeUInt16LE(0, 10);
    centralHeader.writeUInt32LE(0, 12);
    centralHeader.writeUInt32LE(crc, 16);
    centralHeader.writeUInt32LE(data.length, 20);
    centralHeader.writeUInt32LE(data.length, 24);
    centralHeader.writeUInt16LE(nameBuffer.length, 28);
    centralHeader.writeUInt32LE(offset, 42);
    nameBuffer.copy(centralHeader, 46);
    centralParts.push(centralHeader);

    offset += localHeader.length + data.length;
  }

  const centralDirectory = Buffer.concat(centralParts);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(centralParts.length, 8);
  end.writeUInt16LE(centralParts.length, 10);
  end.writeUInt32LE(centralDirectory.length, 12);
  end.writeUInt32LE(offset, 16);

  return Buffer.concat([...localParts, centralDirectory, end]);
}

function crc32(buffer) {
  let crc = 0xffffffff;

  for (const byte of buffer) {
    crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8);
  }

  return (crc ^ 0xffffffff) >>> 0;
}
